@startuml
'https://plantuml.com/component-diagram

node "Account"{
    [user]

}


package "Persistence" {
  [ConnectionPool]-[Hidden]-[UserFacade]
  [ConnectionPool]-[Hidden]-[ItemFacade]
  [ConnectionPool]-[Hidden]-[CarportFacade]
  [UserFacade]
  [UserMapper]
  [ItemFacade]
  [ItemMapper]
  [CarportFacade]
  [CarportMapper]

}


cloud "User" {
  [Login]
  [CreateUser]
}

cloud "Carport"{
  [CreateOrder]
  [AddToOrderLine]
}

cloud "Items"{
    [GetItemList]
    [AddToItemLine]
}

database "MySql" {
  folder "User Data" {
    [Users]
  }
  folder "Order Data"{
    [Orders]
    [OrderLine]
  }
  folder "Item Data" {
      [ItemLine]
      [ItemsList]
  }
}
[user]--[ConnectionPool]
[user]->[UserFacade]
[user]->[ItemFacade]
[user]->[CarportFacade]

[ConnectionPool] - [UserFacade]
[ConnectionPool] - [ItemFacade]
[ConnectionPool] - [CarportFacade]

[UserFacade] --> [UserMapper]
[CarportFacade] --> [CarportMapper]
[ItemFacade] --> [ItemMapper]

[UserMapper] <--> [Login]
[UserMapper] --> [CreateUser]
[CreateUser] --> [Users]
[Login] <--> [Users]

[CarportMapper] --> [CreateOrder]
[CarportMapper] --> [AddToOrderLine]
[CreateOrder] --> [Orders]
[AddToOrderLine] --> [OrderLine]

[ItemMapper] <--> [GetItemList]
[ItemMapper] --> [AddToItemLine]
[GetItemList] <--> [ItemsList]
[AddToItemLine] --> [ItemLine]




@enduml